export interface iGlideJS {
  children : any,
  id ?: string,
  controls ?: boolean,
  arrows ?: boolean,
  bullets ?: boolean,

  quantity ?: number,
  Type ?: "slider" | "carousel",
  StartAt ?: number,
  PerView ?: number,
  FocusAt ?: number,
  Gap ?: number,
  Autoplay ?: number | false | undefined,
  Hoverpause ?: boolean,
  Keyboard ?: boolean,
  Bound ?: boolean,
  SwipeThreshold ?: number | boolean,
  DragThreshold ?: number | boolean,
  PerTouch ?: number | boolean,
  TouchRatio ?: number,
  TouchAngle ?: number,
  AnimationDuration ?: number,
  Rewind ?: boolean,
  RewindDuration ?: number,
  AnimationTimingFunc ?: string,
  Direction ?: string,
  Peek ?: number | Object,
  Breakpoints ?: Object,
  Classes ?: Object,
  Throttle ?: number
}